version: '3.3' # specify docker-compose version


volumes:
  postgres:

# Define the services/containers to be run
services:

  postgres:
    image: postgres:10.4-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"      
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ladb"    
      PGDATA: /var/lib/postgresql/data/pgdata

      
  sonarqube:
    image: sonarqube:7.1-alpine
    restart: always
    ports:
      - "9000:9000"      
      - "9092:9092"  
    environment:
      SONARQUBE_JDBC_USERNAME: "sonar"
      SONARQUBE_JDBC_PASSWORD: "sonar"
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"   
    depends_on: 
      - postgres       
