- hosts: tdv
  become: yes
  vars:
    resolv_searchpath: "{{ dns_resolv_searchpath }}"
    resolv_dns_server: "{{ dns_server_list }}"

  pre_tasks:
  - name: installing openjdk repo in Ubuntu
    apt_repository: repo='ppa:openjdk-r/ppa'
    when: "ansible_os_family == 'Debian'"          
 
  tasks: 
  - name: set timezone to "{{timezone}}"
    timezone:
      name: "{{timezone}}"
    tags:
       - prep
 
  - name: Upload install.properties file
    template:
      src: ../templates/install.properties.j2
      dest: "/home/{{ansible_ssh_user}}/install.properties"
      owner: "{{ansible_ssh_user}}"
      group: "{{ansible_ssh_user}}"
      mode: "u=rw,g=rw,o=r"

  - name: Upload binary TDV to server
    copy:
      src: "./TIB_tdv_server_8.2.0_linux_x86_64.bin"
      dest: "/home/{{ansible_ssh_user}}/."
      owner: "{{ansible_ssh_user}}"
      directory_mode: yes
      group: "{{ansible_ssh_user}}"
      mode: 0755

  - name: Create installation folder with permissions to '1000'
    file:
      path: "/u01"
      owner: 1000
      group: 1000
      state: directory
      recurse: yes
 

  - name: Executing TIBCO TDV Installation in silent-mode
    shell: "./TIB_tdv_server_8.2.0_linux_x86_64.bin --optionfile install.properties"
    args:
      chdir: /home/{{ansible_ssh_user}}/
    become: false
    tags:
      - install


  - name: installs epel-release
    yum:
      name: "oracle-epel-release-el7"
      state: present
    tags:
       - install

  - name: installs python-pip
    yum:
      name: "python-pip"
      state: present
    tags:
       - install

  - name: Install pexpect
    pip:
       name: pexpect
       version: "4.7.0"
       state: present
    tags:
       - install

  - name: Adding TIBCO TDV to auto-start at boot time
    expect: 
      command: /u01/TIBCO/TDV/bin/cis_install_services.sh
      responses:
        (?i)user name: "{{ ansible_ssh_user }}"
    become: true
    ignore_errors: True
    tags:
      - prompt

  - name: Unconditionally reboot the machine with all defaults
    reboot:

  roles:
    - { role: ypsman.resolv }  
    - role: geerlingguy.java 
      when: "ansible_os_family == 'RedHat'"
      vars:
        java_home: "/usr/lib/jvm/java-11-openjdk"
      java_packages:
        - java-11-openjdk


